- src/main.rs
> First try at replacing partials lines

- src/main.rs
- tests/tests/libui-rs/simple/output.txt
- tests/tests/libui-rs/skipping/output.txt
- tests/tests/libui-rs/yolo/output.txt
- tests/tests/use_test/first/output.txt
- tests/tests/use_test/replace_fail/output.txt
- tests/tests/use_test/second/output.txt
> Condense output in presence of multiple suggestions

- Cargo.toml
- cargo-fix/Cargo.toml
- cargo-fix/src/main.rs
- src/bin/cargo-fix.rs
- src/lib.rs
- rustfix stays as the library crate
- cargo-fix becomes the new binary crate
> Split rustfix into two crates

- Cargo.toml
- cargo-fix/Cargo.toml
- cargo-fix/src/lock.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/dependencies.rs
- cargo-fix/tests/all/main.rs
- cargo-fix/tests/all/smoke.rs
- cargo-fix/tests/all/subtargets.rs
- cargo-fix/tests/all/warnings.rs
This commit starts rewritign the `cargo fix` command in line with the recent
discussions around the edition. The main changes here are:
* The interactivity of `cargo fix` is removed
* Executing `cargo fix` is now a thin veneer over `cargo check`
* Fixes are automatically applied when it looks very likely to succeed if we
apply them.
* Fixes are only applied to the local workspace rather than upstream crates as
well.
There's still a number of missing features to fill out marked with a few TODO
here and there but the test suite is already looking relatively solid. I think
we've got a long way to go here but this is hopefully a good start in the
direction of where we want to go.
> Rewrite the `cargo fix` command

- .travis.yml
- Cargo.toml
- cargo-fix/src/main.rs
- cargo-fix/tests/all/main.rs
- cargo-fix/tests/all/smoke.rs
- src/diagnostics.rs
- src/lib.rs
- src/replace.rs
- tests/everything.rs
Addresses #57
Btw, this is still only concerning itself with replacing multiple things in one file. #66 changes the CLI to group suggestions by file. Not sure if we want to make this part of the library.
> Use a more clever way to replace parts of a file

- cargo-fix/tests/all/dependencies.rs
- cargo-fix/tests/all/smoke.rs
Make sure that we always run the version that we're compiling locally
> Fix tests if `cargo fix` is already installed

- cargo-fix/Cargo.toml
- cargo-fix/src/cli.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/broken_build.rs
- cargo-fix/tests/all/subtargets.rs
This commit pulls in `clap` to have a location to actually insert a CLI for
`cargo fix` itself. This'll hopefully allow us to continue to configure
cargo-fix's behavior while also allowing passing arguments down to Cargo.
This starts out by adding a `--broken-code` option which can be used to specify
that previously broken code should be fixed, despite it being originally
broken.
Closes #70
Closes #71
Closes #84
> Start giving `cargo fix` a dedicated CLI

- cargo-fix/Cargo.toml
- cargo-fix/src/cli.rs
- cargo-fix/src/diagnostics.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/dependencies.rs
- cargo-fix/tests/all/main.rs
- cargo-fix/tests/all/smoke.rs
- cargo-fix/tests/all/subtargets.rs
Currently, running `cargo fix` ends up printing a bunch of "Checking …"
lines from the internal `cargo check` calls. In the step where we apply
suggestions, I've now added "Fixing …" lines -- one per file. The style
is the same as cargo's (it's using the same crates and color detection).
based on #82 
concerns #76
> Cargo fix output

- cargo-fix/src/diagnostics.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/broken_build.rs
- cargo-fix/tests/all/main.rs
This commit alters the printing of `Fixing` to not happen if we end up
reverting the fixes that we applied. Instead the message of `Fixing` is delayed
until *after* we've run through the compiler and know that we've fixed the code.
This also updates the `Message::post` method to block until the diagnostic has
finished writing, which fixes a race that was coming up in the test suite.
> Don't print "Fixing" if fixes are reverted

- cargo-fix/src/cli.rs
This is hopefully a little easier to see in contrast to the normal green
"Compiling", and it stood out a bit more for me locally
> Switch "fixing" messages to Cyan

- cargo-fix/src/cli.rs
- cargo-fix/src/diagnostics.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/broken_build.rs
The rustfix tool detects it, so let's inform the user what just happened!
Closes #88
> Warn users when fixes break code

- Cargo.toml
- cargo-fix/src/cli.rs
- cargo-fix/src/diagnostics.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/broken_lints.rs
- cargo-fix/tests/all/main.rs
- src/lib.rs
- src/replace.rs
When rustfix fails to replace a chunk of code, we now display a
similar warning than when we "fixed" the code so that it no longer
compiles.
Previously, when rustfix fails to apply suggestions to a file, we bailed
out of the whole loop over all the files in the current target. Instead,
we'll now log a nice error message. (I'm not sure if that is a good idea
but we will revert non-compiling changes later on anyway.)
> Custom warning when rustfix replacing fails

- cargo-fix/src/cli.rs
- cargo-fix/tests/all/edition_upgrade.rs
- cargo-fix/tests/all/main.rs
This requires
#![feature(crate_in_paths)]
#![deny(absolute_path_starting_with_module)]
on `rustc 1.27.0-nightly (8ff4b4206 2018-05-08)`, so we're not really there yet.
> Add `--prepare-for` flag

- cargo-fix/tests/all/edition_upgrade.rs
* Internal `use` paths should be rewritten to `crate::` where possible
* Internal `use` paths should not be rewritten if the feature isn't enabled
* `extern crate foo` directives should be removed
> Add tests for some edition lints

- .appveyor.yml
- cargo-fix/src/cli.rs
- cargo-fix/src/diagnostics.rs
- cargo-fix/src/main.rs
- cargo-fix/src/vcs.rs
- cargo-fix/tests/all/main.rs
- cargo-fix/tests/all/vcs.rs
This builds on @BrainMaestro's #104 and changes only the way/what we output. I've also added an "ignore VSC state" env var that the integration tests can use. See the commit message for more details.
Just like #104 (and only repeating for Github to pick it up), this:
Closes #75
Closes #74
> Add warning for "no VSC" and "dirty working dir"

- Cargo.toml
- tests/parse_and_replace.rs
Setting RUST_LOG without filtering it causes integration tests to fail
because it changes the output of rustc. By upgrading duct to 0.9 we get
env_remove which we can use to filter out the RUST_LOG setting and not
pass it down to rustc.
feel free to ignore this one, it's not tied to any issue. I was just annoyed by the fact that I had to manually filter my RUST_LOG environment variable or else it would cause the tests to start failing. It would probably bother me less if I looked up how RUST_LOG worked and figured out how to set it for all tests, it was annoying needing to move around the filter.
> Dont pass RUST_LOG to rustc subprocess in tests

- cargo-fix/tests/all/main.rs
This prevents the std{err,out} assertions from failing because of unexpected log output.
> Overwrite RUST_LOG env var in cargo-fix tests

- cargo-fix/src/cli.rs
- cargo-fix/src/main.rs
- cargo-fix/tests/all/broken_build.rs
- cargo-fix/tests/all/broken_lints.rs
- cargo-fix/tests/all/dependencies.rs
- cargo-fix/tests/all/edition_upgrade.rs
- cargo-fix/tests/all/main.rs
- cargo-fix/tests/all/smoke.rs
- cargo-fix/tests/all/subtargets.rs
- cargo-fix/tests/all/vcs.rs
- examples/fix-json.rs
- src/diagnostics.rs
- src/lib.rs
- tests/edge_cases.rs
- tests/parse_and_replace.rs
Finally -- we have a way to indicate that we trust a lint! This is currently an unstable feature in rustc and thus requires nightly.
The first lints that are currently as machine applicable land with <https://github.com/rust-lang/rust/pull/50454>, so adding tests will have to wait for a bit -- see #95.
(this is currently based on #96)
> Filter by machine applicability

- cargo-fix/src/cli.rs
- cargo-fix/tests/all/vcs.rs
(From [discussion](https://github.com/rust-lang-nursery/rustfix/pull/109#discussion_r189385729) on no. 109.)
> "rustfix'" → "rustfix's"

- cargo-fix/src/main.rs
This resolves #113, and plausibly also #115.
> reset terminal color/bold after emitting error

- cargo-fix/src/cli.rs
When RUSTFLAGS was set, we would previously use "§{RUSTFLAGS}-W rust-2018-compatibility" which can cause
errorous invocations like "cargo fix .... -C target-cpu=native-W rust-2018-compatibility ...." if --prepare-for 2018 is used.
We need an extra space to separate RUSTFLAGS and "-W rust-2018-compatibility" because we want
"-C target-cpu=native -W rust-2018-compatibility".
> cli: fix injection of --prepare-for flags

- src/replace.rs
Currently the compiler suffers from bugs like rust-lang/rust#51211 where it will
emit duplicate suggestions for code that originates in a macro. This commit
allows rustfix to accept and process these suggestions by ignoring exact
duplicates of replacements. While not a great solution long term it should
hopefully be a non-harmful band-aid until rustc is fixed!
> Ignore duplicate replacements

- src/lib.rs
This commit exposes an interface that Cargo can use to apply fixes one-by-one
and know which fixes failed and which succeeded.
> Expose an interface to apply fixes on-by-one

- tests/parse_and_replace.rs
Cargo respects this environment variable (to specify the path to what
rustc binary to use), but the Rustfix test suite did not. However, this
capability is useful when developing new compiler diagnostics that one
wants Rustfix to be able to handle (this being inspired by the endeavor
that is rust-lang/rust#53013).
> use RUSTC environment var in `parse_and_replace::compile` if present

- src/diagnostics.rs
This is so that Cargo can show a rendered diagnostic: https://github.com/rust-lang/cargo/pull/6419
> Make Diagnostic::rendered public.

- src/lib.rs
- tests/edge-cases/out_of_bounds.recorded.json
- tests/edge_cases.rs
> Fix out of bounds access in parse_snippet

- examples/fix-json.rs
This is something I hacked together to allow me to automatically apply some clippy fixes. Not sure if this is something that is desired, but I thought I'd share in case others find it useful (eg see #130). Note that this overwrites the existing files. Also I know nothing about the json format for the suggestions, I'm probably making assumptions that I shouldn't.
My usage is:
```
cargo clippy --message-format json | jq .message | grep -v ^null > clippy.json
fix-json clippy.json
```
> Change example to automatically determine filename

- src/lib.rs
- tests/edge-cases/utf8_idents.recorded.json
- tests/edge_cases.rs
Previously rustfix was treating the highlight indices as byte offsets.
This caused it to crash when a highlight index was pointing inside a
multi-byte character.
This fix makes sure to index into the characters of the string instead
of the bytes.
Fixes https://github.com/rust-lang/rust/issues/59660
> Fix string indexing

- tests/everything/E0178.fixed.rs
- tests/everything/E0178.rs
- tests/everything/closure-immutable-outer-variable.fixed.rs
This should get tests passing on CI.
`bare_trait_objects` was made warn-by-default in https://github.com/rust-lang/rust/pull/61203.
E0178 can't fix both diagnostics because they overlap.
> Update tests for `bare_trait_objects` warning.

- Cargo.toml
- examples/fix-json.rs
- src/lib.rs
- src/replace.rs
- tests/parse_and_replace.rs
This moves from a custom error trait to the standard `Error` trait,
improving ecosystem interoperability.
> Migrate from `failure` to `anyhow`

- src/lib.rs
- tests/edge-cases/empty.json
- tests/edge-cases/no_main.json
- tests/edge-cases/no_main.rs
- tests/edge_cases.rs
- tests/parse_and_replace.rs
Fixes a few cases where rustfix will panic.
* An empty file (where there are no lines).
* Span pointing at the end of the file.
> Fix some panics in edge cases.

- Cargo.toml
- tests/parse_and_replace.rs
Since difference.rs is unmaintained I made the liberty of creating a pull request replacing it with my similar crate.
For more information see https://rustsec.org/advisories/RUSTSEC-2020-0095.html
> Switch to similar from difference

- src/lib.rs
- tests/edge-cases/indented_whitespace.json
- tests/edge_cases.rs
There is a bug where rustfix would panic on input where the `highlight_start` appears within whitespace characters.  The issue is that the code computing the indent was comparing the indent (which is 0-based) to the `highlight_start` (which is 1-based).  All the following code expects 0-based offsets.
In this particular example, the `let lead = text_slice[indent..start]` would panic because indent is 1 whereas `start` is 0.
> Fix panic computing indentation.

- src/lib.rs
- src/replace.rs
```
warning: this expression borrows a reference (`&std::rc::Rc<[u8]>`) that is immediately dereferenced by the compiler
--> src/replace.rs:59:90
|
59 |                 State::Replaced(ref d) | State::Inserted(ref d) => acc.extend_from_slice(&d),
|                                                                                          ^^ help: change this to: `d`
|
= note: `#[warn(clippy::needless_borrow)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
warning: this expression borrows a reference (`&[replace::Span]`) that is immediately dereferenced by the compiler
--> src/replace.rs:167:45
|
167 |                 new_parts.extend_from_slice(&ps);
|                                             ^^^ help: change …
```
> Fix few clippy lints

- Cargo.toml
The `anyhow` crate intentionally breaks semver rules, and adds new features in "patch" releases. This crate uses `ensure` macro that has been added in a version after 1.0.0.
(the serde dependency is probably broken too, for the same reason)
> Fix for anynow causing semver-breakage

- src/diagnostics.rs
I'm writing a tool using rustfix that needs to know about primary spans. Currently it relies on the fact that the last span in the list emitted by rustc happens to be a primary one, but it'd be nice if this field was just exposed on the diagnostic itself.
> Make Diagnostic::is_primary public

- Cargo.toml
This PR bumps `rustfix`'s version from `0.6.0` to `0.6.1`.
I scanned the commits since the [last release](https://github.com/rust-lang/rustfix/commit/e6dabf15236e0a1bb05fc54718cb5f83b0e82da5), and none of them appear to be breaking.
Note that https://github.com/rust-lang/rustfix/pull/207 does expand `rustfix`'s API. But given how Cargo [handles semantic versioning](https://doc.rust-lang.org/cargo/reference/semver.html), this fact only warrants a bump of `z` in `0.y.z`.
> Prepare for new release

- Readme.md
Hello,
Following on from #221 I thought I would have a go at improving the README a little. I've looked at this crate several times in the past thinking it did something different to what it actually did!
Please feel free to correct anything I've put that isn't correct. The goal is to let people know what the library does, as well as directing them that what they're looking for probably isn't here.
Max
> README update aiming to clarify things for less experienced rustaceans

- src/lib.rs
- src/replace.rs
Previously trying to insert some code at the very beginning seems to have caused issues.
Using start=0, end=0 means "replace the first character with the given data", so to properly insert at the beginning the code should call `.replace_range(0, -1, b"...")` (not possible because `-1` is not an `usize`). This commit fixes that by using exclusive ranges instead, so now `.replace_range(0..0, b"...")` inserts at the beginning.
> fix insert at beginning
